### ISSUE TITLE
lcpan update failed

### ISSUE THREAD

**Issue by hakonhagland** [perlancar/perl-App-lcpan#1]
Hi. I just installed `App::lcpan` with `cpanm App::lcpan` then I ran `lcpan update` from the command line. After some hours of downloading the command aborted with error message:

```
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::SQLite::db handle dbname=/home/hakon/cpan/index.db at /usr/share/perl/5.20/Pod/Simple/BlackBox.pm line 380.
lcpan: ERROR 500: Died: Nested processed encoding. at /usr/share/perl/5.20/Pod/Simple/BlackBox.pm line 380.
```

I am using Perl version 5.20.2 on Ubuntu 15.10.

**Comment by perlancar** [comment]
Sorry, missed this PR/issue (didn't receive notification from GitHub).

Norbert Csongradi offered a fix, and I'm including it in the next release. Thanks!
