### ISSUE TITLE
lcpan mentions : ERROR 500: Get args from array failed 

### ISSUE THREAD

**Issue by hakonhagland** [perlancar/perl-App-lcpan#4]
`lcpan mentions XML::RSS` gives me following error:

```
lcpan: ERROR 500: Get args from array failed (400: There are extra, unassigned elements in array: [XML::RSS])
```

The same error with other module names.

**Comment by perlancar** [comment]
Sorry for the very late response. I didn't see the notification for this issue.

What did you intend to do? The usage for mentions (`lcpan mentions --help`) does indicate that the subcommand does not accept command-line arguments, only options.

If you want to know what pages mentions XML::RSS, try:

    % lcpan mentions --mentioned-module XML::RSS

If you want to know what other modules the XML::RSS POD mentions:

    % lcpan mentions --mentioner-module XML::RSS

Hope that helps.
